- doc/conf.py
- setup.py
but had to hard-code current version to do it. Something is messing with the ability to autogenerate docs when the current version is imported from scadnano
> fixed documentation

- .github/workflows/release.yml
Based on this: https://github.com/readthedocs/readthedocs.org/issues/4868, seems like "latest" tag is confusing readthedocs.
> Change default tag from latest to current

- .github/workflows/python-publish.yml
@dave-doty Can you add the necessary secrets named `PYPI_USERNAME` and `PYPI_PASSWORD` to the [repositories' secrets](https://github.com/UC-Davis-molecular-computing/scadnano-python-package/settings/secrets). I tried this out with my [local fork secrets](https://github.com/UnHumbleBen/scadnano-python-package-1/settings/secrets) and it seems pretty safe in the sense that there is no way you can see the value of the secret that you entered. Even if you try to update them, Github will not show what was the previous value of the secret.
> Setup workflow to publish to PyPI

- .github/workflows/check_pypi_packaging.yml
- .github/workflows/docs-check.yml
- .github/workflows/run_unit_tests.yml
This fixes issue where PR from external forks would not have
CI checks, as in [this PR](https://github.com/UC-Davis-molecular-computing/scadnano-python-package/pull/142).
This commit fixes this issue, as shown in this
[sample PR](https://github.com/UnHumbleBen/scadnano-python-package-1/pull/5).
You can see that CI tests run now.
> Adds PR to CI workflow

- scadnano/scadnano.py
I noticed a little message showing up while running some dsd sequence design: I think this statement snuck in here and avoided getting removed. (Now on dev branch.)
> Remove debug print hello in to_idt_bulk_input_format

- examples/1_staple_1_helix_origami_position_nondefault.py
- examples/4_helix_grid_none.py
- examples/output_designs/1_staple_1_helix_origami_position_nondefault.sc
- scadnano/scadnano.py
- tests/scadnano_tests.py
- tests_inputs/cadnano_v2_export/test_16_helix_origami_rectangle_no_twist.sc
- tests_inputs/cadnano_v2_export/test_2_stape_2_helix_origami_deletions_insertions.sc
- tests_inputs/cadnano_v2_export/test_2_stape_2_helix_origami_extremely_simple.sc
- tests_inputs/cadnano_v2_export/test_2_stape_2_helix_origami_extremely_simple_2.sc
- tests_inputs/cadnano_v2_export/test_6_helix_origami_rectangle.sc
- tests_inputs/cadnano_v2_export/test_circular_strand.sc
- tests_inputs/cadnano_v2_export/test_export_design_with_helix_group.sc
- tests_inputs/cadnano_v2_export/test_export_design_with_helix_group_not_same_grid.sc
I still have not implemented a Design method for looking up pitch/yaw/roll values for helices. Should be straightforward, but any name suggestions for the function names? Maybe `Design.{pitch/yaw/roll}_of_helix`?
The second reason for not merging yet is because I added code in `Design.json` to allow for compatibility with designs that specified pitch and yaw in individual Helix. It passes all of the old test cases as well as news one I made, but I am concerned about the quality of the implementation so I would like to give @dave-doty an opportunity to review the code.
* Remove Helix.pitch and Helix.yaw
* Update Design.from_json to be compatible with designs that specified
pitch and yaw in individual Helix (except when multiple helices in the
same group have different pitch/yaw values, in …
> Fixes #163; Remove Helix.pitch and Helix.yaw

- scadnano/scadnano.py
Using re.sub (re is already imported), along with a replacement function that pulls from the replacement map, avoids repeated string replacements within Python and significantly speeds up encoding for large files.  Note that I think this will raise a KeyError if the user has something with a name fitting "@@(\d+)@@" where the number is larger than the largest unique_id, and will corrupt the file if it is not. However, this is similar to the current situation, where I think it will never raise an error, but could corrupt the file.
This also changes the type of _replacement_map to avoid a mypy warning: it should be a correct narrowing of the value from Any to str, however.
Trying this with the design I'm trying to repeatedly save, the change brings write time down from 20 seconds to a …
> Encoder indent suppression: str.replace → re.sub (fixes #170)

- scadnano/scadnano.py
See if the fixing Sphinx warning `Field list ends without a blank line; unexpected unindent.` will allow the  [Docs Check workflow](https://github.com/UC-Davis-molecular-computing/scadnano-python-package/actions/workflows/docs-check.yml) to pass.
> Fix Sphinx warning on idt_dna_sequence

- scadnano/scadnano.py
minor typo here in the export that puts the scale both where it should be and where the purification should be
> fix purification/scale typo in to_idt_bulk_input_format

- scadnano/scadnano.py
When applying the roll angle to a helix, the function _oxdna_get_helix_vectors was applying the roll angle in the wrong orientation (counterclockwise instead of clockwise). This fix simply flips the direction in which the roll is applied.
> Oxdna export roll angle fix

- setup.py
Moved 'xlwt' from `requires` to `install_requires`. [Dependencies are supposed to be specified in install_requires](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#dependency-management). I couldn't find a clear reason why `requires` is not valid, but I do see in the [setuptools keywords page](https://setuptools.pypa.io/en/latest/references/keywords.html) that:
> requires is superseded by install_requires and should not be used anymore.
#205 
Currently, `xlwt` is not installed when scadnano is installed using `pip`.
Setup: Used new setup.py to make new PyPI test package: https://pypi.org/project/scadnano-test/
1. Uninstall xlwt with `pip uninstall xlwt`
2. Install scadnano-test `pip install scadnano-test`
3. Open a python shell and ran `import xlwt` and verified no import …
> Fixes #205; make xlwt a dependency for pip installing

- scadnano/scadnano.py
Bump version to 0.17.1
[scadnano 0.17.0](https://pypi.org/project/scadnano/0.17.0/) was mistakenly deployed to PyPI so can no longer be pushed to.
> Bump version to 0.17.1

- scadnano/scadnano.py
- tests/scadnano_tests.py
Added field `connector_length` to `Modification` abstract base class.
#212
See https://github.com/UC-Davis-molecular-computing/scadnano/issues/743.
Added check to JSON unit tests with a non-default modification with connector length 6. Verified 6 is properly written, but no JSON is written for default value 4.
> fixes #212: change length of modification "connector"

- scadnano/scadnano.py
A typo was present in cadnano2 export code where key "stap_loop" was used instead of "stapLoop".
> stap_loop -> stapLoop in cadnano export 

- scadnano/scadnano.py
- setup.py
If IDT fields are specified with plate and well positions, scadnano should be able to write a plate map showing strand names in the well positions.
The method `Design.plate_maps_markdown` was implemented, which outputs Markdown representations of plate maps.
#210
This helps to organize and visualize strands in an experiment by visually laying out where the strands are in a 96-well or 384-well plate.
No unit tests. The example in the issue #210 was run, and some other examples for a current wet lab project.
> #210 generate plate map

- README.md
- examples/2_staple_2_helix_origami_deletions_insertions_mods_chained_methods.py
- examples/circular.py
- examples/helix_groups.py
- examples/names_domains_strands.py
- examples/tutorial-examples/24_helix_rectangle.py
- scadnano/scadnano.py
- tests/scadnano_tests.py
- tutorial/tutorial.md
Changed the method `Design.strand` to `Design.draw_strand`, and added a printed warning about deprecation to the old method `Design.strand`, before it simply calls `Design.draw_strand`.
#219 
The method `Design.strand` was poorly named. `Design.draw_strand` better describes what it does.
All unit tests pass.
> closes #219: change `Design.strand` to `Design.draw_strand`

- scadnano/scadnano.py
- tests/scadnano_tests.py
Main changes to review:
* [Replace Strand.dna_sequence field with Strand.dna_sequence() and replace Domain.dna_sequence() with Domain.dna_sequence](https://github.com/UC-Davis-molecular-computing/scadnano-python-package/commit/7515d1af6b002039e7a96355f8656fab1da1e981)
* Test cases assertions rewritten so that domains store expected sequence
* Reimplemented functions
* [`Strand.insert_domain`](https://github.com/UC-Davis-molecular-computing/scadnano-python-package/commit/8c76c993004144ca716d00e74e89c3e555408c8e)
* [`Strand.remove_domain`](https://github.com/UC-Davis-molecular-computing/scadnano-python-package/commit/6ee681120ab903b1a3a1488e13976467bfedd6cd)
* [`Strand.ligate`](https://github.com/UC-Davis-molecular-computing/scadnano-python-package/commit/969ecbc4b85d12853703b2b7a25eb85ae046 …
> Closes #149; store DNA sequence in domains and loopouts, not in strand

- .github/workflows/run_unit_tests.yml
- scadnano/scadnano.py
- setup.py
- tests/scadnano_tests.py
Adds new features to plate maps.
#222 and #224
This makes the method `Design.plate_maps()` (previously called `plate_maps_markdown()`) more useful.
Just one fragile unit test with a strong comparison.
> #224 allow other table formats besides markdown in design.plate maps markdown

- scadnano/scadnano.py
- setup.py
- tests/scadnano_tests.py
Added error-checking code when automatically adding nicks when `Design.add_full_crossover`.
#231
Ill-defined behavior happened previously, editing the design in strange ways. This explicitly fails and alerts the user they need to add the crossover somewhere that a crossover does not already exist.
Some unit tests where added testing `Design.add_full_crossover` and `Design.add_half_crossover` when there is already a crossover at the position.
> fixes #231: Design.add_full_crossover and Design.add_half_crossover should check for existing crossovers

- scadnano/scadnano.py
Mutable defaults in dataclasses will cause an error in Python 3.11.  HelixGroup has a Position3D default.  Position3D appears to be intended to be immutable, and is never used mutably in the code, but does not have `frozen=True` set for the dataclass options.  This sets it, and causes tests to pass with Python 3.11.0b4.
Alternatively, Position3D could be left as is, and the HelixGroup position could be made to be `position: Position3D = field(default_factory=lambda: Position3D(x=0,y=0,z=0))`, but this seems less efficient.
> Set Position3D as frozen

- scadnano/scadnano.py
- tests/scadnano_tests.py
> Add filename extensions to oxDNA exports with filename_no_extension set.

- scadnano/scadnano.py
- tests/scadnano_tests.py
Oxview's format is largely similar to a json version of oxDNA files, though we can also set the color of each nucleotide.
This code is currently messy, and needs tests and documentation.  It currently exports correctly with my large tile systems, but I haven't tested it more thoroughly. 
Closes #173.
> Oxview export

- scadnano/scadnano.py
- tests/scadnano_tests.py
Closes #238: Domain colors.
Not much needed here, just JSON support, and added a `StrandBuilder.with_domain_color()` method for chained method strand creation.
> closes #238: Domain colors

- scadnano/scadnano.py
Changed the type of `label` field in `Strand`, `Domain`, `Loopout`, and `Extension` to `str` instead of an arbitrary object.
#261 
Supporting arbitrary data is more complex, both for the type checking (requiring some ugly `Generic` declarations), and for trying to serialize and deserialize automatically. Instead users can serialize and deserialize manually using the `json` package:
```python
import json
nums = [1, 2, 3]
strand.label = json.dumps(nums)  # stores strand.label as the string '[1, 2, 3]'
nums = json.loads(strand.label)  # nums is now the list [1, 2, 3]
```
Mostly just changed type hints, so checked that there are no mypy errors.
> closes #261: change `label` type to `str`

- scadnano/scadnano.py
- tests/scadnano_tests.py
Fixes bug about ignore loopouts when relaxing Helix rolls.
#268
> fixes #268: ignore loopouts when relaxing Helix rolls

- examples/draw_strand_move_negative.py
- examples/output_designs/draw_strand_move_negative.sc
- scadnano/scadnano.py
- tests/scadnano_tests.py
Ignore "same helix" crossovers when calculating helix rolls. Also ensures that domains stored on a helix (stored in field `Helix._domains`, calculated when calling `Design._build_domains_on_helix_lists`) stores domains in sorted order of start offset (breaking ties with forward/reverse).
#270
> 270 ignore same helix crossovers when calculating helix rolls

- scadnano/scadnano.py
- tests/scadnano_tests.py
Ignores inter-group crossovers when relaxing helix rolls.
#273
> fixes #273: deal with inter-group crossovers when relaxing helix rolls

- environment.yml
- readthedocs.yml
In ``build.tools.python`` in readthedocs.yml, I changed the value to mambaforge. According to the docs, https://docs.readthedocs.io/en/stable/config-file/v2.html#conda, it says it's
> it’s required to specify build.tools.python to tell Read the Docs to use whether Conda or Mamba to create the environment.
Which could be the cause of the build error. I moved ``python=3.7`` to ``environment.yml`` instead.
> Changed to use mamba

- environment.yml
The last pull request failed but for a completely different issue now so hopefully we are still moving forward.
The issue now is that it appears to be that some packages aren't installed when we push to readthedocs.org.
In the Github action, I saw that it runs ``pip install sphinx sphinx_rtd_theme openpyxl`` before building. However, I found that nowhere else does it specify to install these packages when publishing to readthedocs.org, so I added the requirements to ``environment.yml``.
> Added pip packages to enviornment.yml

- scadnano/scadnano.py
closes issue #309
Before this change, helix group rotation wasn't correctly applied to helices during oxDNA export
This change fixes this by applying the helix group rotation to each helix before being translated by the helix group's origin position
This change also avoids using the `Design.roll_of_helix(helix)` since this gives the cumulative roll of the helix plus the roll of the group
Now, the helix group's roll is applied to the helix to determine it's global positions while the helix's individual roll is accounted for by separately rotating the normal axis returned by `_oxdna_get_helix_vectors`
#309 
Note the rolls of the helices as indicated by the slice bar
These are represented in the rolls of the exported helices
> Close Issue #309: account for helix group rotation properly
